package exception_handling;

public class Finally4 {
	public static void main(String [] args) {
		
		int a=20;
		int b=0;
		try {
			
			System.out.println(" i am from nagpur");
		
			
		}
		catch(Exception d) {
			System.out.println("exception handled");
			
		}
		finally {
			System.out.println("thank for man");
		}
	
		
	}

}
